list=[]
l1=input("enter a element to add in list")
list.append(l1)
l2=input("enter a element to add in list")
list.append(l2)
l3=input("enter a element to add in list")
list.append(l3)
l4=input("enter a element to add in list")
list.append(l4)
l5=input("enter a element to add in list")
list.append(l5)
l6=input("enter a element to add in list")
list.append(l6)
l7=input("enter a element to add in list")
list.append(l7)
l8=input("enter a element to add in list")
list.append(l8)
l9=input("enter a element to add in list")
list.append(l9)
l10=input("enter a element to add in list")
list.append(l10)
l11=input("enter a element to add in list")
list.append(l11)
l12=input("enter a element to add in list")
list.append(l12)
l13=input("enter a element to add in list")
list.append(l13)
l14=input("enter a element to add in list")
list.append(l14)
l15=input("enter a element to add in list")
list.append(l15)
l16=input("enter a element to add in list")
list.append(l16)
l17=input("enter a element to add in list")
list.append(l17)
l18=input("enter a element to add in list")
list.append(l18)
l19=input("enter a element to add in list")
list.append(l19)
l20=input("enter a element to add in list")
list.append(l20)
l21=input("enter a element to add in list")
list.append1(l21)
print(list)
