list=[]
li1=input("enter a element to add to the list: ")
list.append(li1)
li2=input("enter a element to add to the list: ")
list.append(li2)
li3=input("enter a element to add to the list: ")
list.append(li3)
li4=input("enter a element to add to the list: ")
list.append(li4)
li5=input("enter a element to add to the list: ")
list.append(li5)
li6=input("enter a element to add to the list: ")
li7=input("enter a element to add to the list: ")
list.append(li7)
print("the list is:",list)
