list=[]
Fruit1=input("enter a fruit name to add in list")
list.append(Fruit1)
Fruit2=input("enter a fruit name to add in list")
list.append(Fruit2)
Fruit3=input("enter a fruit name to add in list")
list.append(Fruit3)
Fruit4=input("enter a fruit name to add in list")
list.append(Fruit4)
Fruit5=input("enter a fruit name to add in list")
list.append(Fruit5)
Fruit6=input("enter a fruit name to add in list")
list.append(Fruit6)
Fruit7=input("enter a fruit name to add in list")
list.append(Fruit7)
print(list)